begin;

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique check (username is null or char_length(username) between 3 and 30),
  display_name text not null default 'Atleta' check (char_length(display_name) between 2 and 40),
  avatar_url text,
  bio text not null default '' check (char_length(bio) <= 600),
  city text not null default '' check (char_length(city) <= 80),
  level text not null default 'beginner' check (level in ('beginner', 'intermediate', 'advanced')),
  reliability_score numeric(5,2) not null default 100 check (reliability_score between 0 and 100),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.sports (
  id smallint generated by default as identity primary key,
  slug text not null unique,
  name text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.events (
  id uuid primary key default gen_random_uuid(),
  creator_id uuid not null references public.profiles(id) on delete cascade,
  sport_id smallint not null references public.sports(id) on delete restrict,
  title text not null check (char_length(title) between 4 and 100),
  description text not null default '' check (char_length(description) <= 2000),
  city text not null default '' check (char_length(city) <= 80),
  location_name text not null check (char_length(location_name) between 3 and 180),
  lat double precision check (lat is null or lat between -90 and 90),
  lng double precision check (lng is null or lng between -180 and 180),
  starts_at timestamptz not null,
  duration_minutes smallint not null default 120 check (duration_minutes between 15 and 720),
  max_participants smallint not null check (max_participants between 2 and 500),
  required_level text not null default 'beginner'
    check (required_level in ('beginner', 'intermediate', 'advanced', 'all')),
  route_info jsonb,
  status text not null default 'scheduled'
    check (status in ('scheduled', 'cancelled', 'completed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.event_participants (
  event_id uuid not null references public.events(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'going' check (status in ('going', 'cancelled', 'completed', 'no_show')),
  skill_level text not null default 'beginner'
    check (skill_level in ('beginner', 'intermediate', 'advanced')),
  note text not null default '' check (char_length(note) <= 500),
  joined_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (event_id, user_id)
);

create table if not exists public.saved_events (
  user_id uuid not null references public.profiles(id) on delete cascade,
  event_id uuid not null references public.events(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, event_id)
);

create table if not exists public.event_messages (
  id bigint generated always as identity primary key,
  event_id uuid not null references public.events(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 1000),
  created_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id bigint generated always as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  actor_id uuid references public.profiles(id) on delete set null,
  event_id uuid references public.events(id) on delete cascade,
  type text not null check (char_length(type) between 2 and 60),
  title text not null check (char_length(title) between 2 and 120),
  body text not null default '' check (char_length(body) <= 500),
  payload jsonb not null default '{}'::jsonb,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists events_starts_at_idx on public.events(starts_at);
create index if not exists events_sport_starts_idx on public.events(sport_id, starts_at);
create index if not exists events_creator_idx on public.events(creator_id);
create index if not exists event_participants_user_status_idx
  on public.event_participants(user_id, status);
create index if not exists event_messages_event_created_idx
  on public.event_messages(event_id, created_at);
create index if not exists notifications_user_created_idx
  on public.notifications(user_id, created_at desc);
create index if not exists notifications_user_unread_idx
  on public.notifications(user_id, created_at desc)
  where read_at is null;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists events_set_updated_at on public.events;
create trigger events_set_updated_at
before update on public.events
for each row execute function public.set_updated_at();

drop trigger if exists event_participants_set_updated_at on public.event_participants;
create trigger event_participants_set_updated_at
before update on public.event_participants
for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  insert into public.profiles (id, display_name)
  values (
    new.id,
    coalesce(
      nullif(trim(new.raw_user_meta_data ->> 'display_name'), ''),
      nullif(split_part(coalesce(new.email, ''), '@', 1), ''),
      'Atleta'
    )
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.add_event_creator_as_participant()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  insert into public.event_participants (event_id, user_id, status)
  values (new.id, new.creator_id, 'going')
  on conflict (event_id, user_id) do update set status = 'going', updated_at = now();
  return new;
end;
$$;

drop trigger if exists on_event_created on public.events;
create trigger on_event_created
after insert on public.events
for each row execute function public.add_event_creator_as_participant();

create or replace function public.is_event_participant(target_event_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1
    from public.event_participants
    where event_id = target_event_id
      and user_id = auth.uid()
      and status = 'going'
  );
$$;

create or replace function public.join_event(
  target_event_id uuid,
  participant_skill_level text default 'beginner',
  participant_note text default ''
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  actor_id uuid := auth.uid();
  target_event public.events%rowtype;
  existing_status text;
  occupied integer;
begin
  if actor_id is null then
    raise exception 'Devi accedere per partecipare';
  end if;

  if participant_skill_level not in ('beginner', 'intermediate', 'advanced') then
    raise exception 'Livello non valido';
  end if;

  select *
  into target_event
  from public.events
  where id = target_event_id
  for update;

  if not found then
    raise exception 'Evento non trovato';
  end if;
  if target_event.status <> 'scheduled' then
    raise exception 'Evento non disponibile';
  end if;
  if target_event.starts_at <= now() then
    raise exception 'Evento gia iniziato';
  end if;

  select status
  into existing_status
  from public.event_participants
  where event_id = target_event_id and user_id = actor_id;

  if existing_status = 'going' then
    return jsonb_build_object('success', true, 'already_joined', true);
  end if;

  select count(*)
  into occupied
  from public.event_participants
  where event_id = target_event_id and status = 'going';

  if occupied >= target_event.max_participants then
    raise exception 'Evento completo: posti disponibili terminati';
  end if;

  insert into public.event_participants (
    event_id,
    user_id,
    status,
    skill_level,
    note,
    joined_at,
    updated_at
  )
  values (
    target_event_id,
    actor_id,
    'going',
    participant_skill_level,
    left(coalesce(participant_note, ''), 500),
    now(),
    now()
  )
  on conflict (event_id, user_id) do update
  set
    status = 'going',
    skill_level = excluded.skill_level,
    note = excluded.note,
    joined_at = now(),
    updated_at = now();

  insert into public.notifications (user_id, actor_id, event_id, type, title, body)
  values (
    actor_id,
    actor_id,
    target_event_id,
    'rsvp_confirmed',
    'Partecipazione confermata',
    target_event.title
  );

  return jsonb_build_object(
    'success', true,
    'already_joined', false,
    'participants_count', occupied + 1
  );
end;
$$;

create or replace function public.leave_event(target_event_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  actor_id uuid := auth.uid();
  target_event public.events%rowtype;
begin
  if actor_id is null then
    raise exception 'Devi accedere per abbandonare un evento';
  end if;

  select *
  into target_event
  from public.events
  where id = target_event_id
  for update;

  if not found then
    raise exception 'Evento non trovato';
  end if;
  if target_event.creator_id = actor_id then
    raise exception 'L organizzatore non puo abbandonare il proprio evento';
  end if;

  update public.event_participants
  set status = 'cancelled', updated_at = now()
  where event_id = target_event_id
    and user_id = actor_id
    and status = 'going';

  if not found then
    raise exception 'Non risulti tra i partecipanti';
  end if;

  return jsonb_build_object('success', true);
end;
$$;

create or replace function public.notify_event_participation()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  event_owner uuid;
  event_title text;
  participant_name text;
begin
  select creator_id, title into event_owner, event_title
  from public.events
  where id = new.event_id;

  if event_owner is null or event_owner = new.user_id then
    return new;
  end if;

  select display_name into participant_name
  from public.profiles
  where id = new.user_id;

  if new.status = 'going' and (tg_op = 'INSERT' or old.status is distinct from 'going') then
    insert into public.notifications (user_id, actor_id, event_id, type, title, body)
    values (
      event_owner,
      new.user_id,
      new.event_id,
      'participant_joined',
      'Nuovo partecipante',
      coalesce(participant_name, 'Un atleta') || ' partecipa a ' || event_title
    );
  elsif new.status = 'cancelled' and tg_op = 'UPDATE' and old.status is distinct from 'cancelled' then
    insert into public.notifications (user_id, actor_id, event_id, type, title, body)
    values (
      event_owner,
      new.user_id,
      new.event_id,
      'participant_left',
      'Partecipazione annullata',
      coalesce(participant_name, 'Un atleta') || ' ha lasciato ' || event_title
    );
  end if;

  return new;
end;
$$;

drop trigger if exists on_event_participation_changed on public.event_participants;
create trigger on_event_participation_changed
after insert or update of status on public.event_participants
for each row execute function public.notify_event_participation();

create or replace function public.notify_event_message()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  event_title text;
  sender_name text;
begin
  select title into event_title from public.events where id = new.event_id;
  select display_name into sender_name from public.profiles where id = new.sender_id;

  insert into public.notifications (user_id, actor_id, event_id, type, title, body)
  select
    participant.user_id,
    new.sender_id,
    new.event_id,
    'event_group_message',
    coalesce(event_title, 'Chat evento'),
    coalesce(sender_name, 'Partecipante') || ': ' || left(new.body, 180)
  from public.event_participants participant
  where participant.event_id = new.event_id
    and participant.status = 'going'
    and participant.user_id <> new.sender_id;

  return new;
end;
$$;

drop trigger if exists on_event_message_created on public.event_messages;
create trigger on_event_message_created
after insert on public.event_messages
for each row execute function public.notify_event_message();

insert into public.sports (id, slug, name) values
  (1, 'running', 'Running'),
  (2, 'padel', 'Padel'),
  (3, 'calcio', 'Calcio'),
  (4, 'palestra', 'Palestra'),
  (5, 'bici', 'Bici'),
  (6, 'trekking', 'Trekking')
on conflict (id) do update set slug = excluded.slug, name = excluded.name;

select setval(
  pg_get_serial_sequence('public.sports', 'id'),
  greatest((select coalesce(max(id), 1) from public.sports), 1),
  true
);

alter table public.profiles enable row level security;
alter table public.sports enable row level security;
alter table public.events enable row level security;
alter table public.event_participants enable row level security;
alter table public.saved_events enable row level security;
alter table public.event_messages enable row level security;
alter table public.notifications enable row level security;

drop policy if exists "profiles_read_authenticated" on public.profiles;
create policy "profiles_read_authenticated"
on public.profiles for select
to authenticated
using (true);

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own"
on public.profiles for insert
to authenticated
with check ((select auth.uid()) = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
on public.profiles for update
to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

drop policy if exists "sports_read_all" on public.sports;
create policy "sports_read_all"
on public.sports for select
to anon, authenticated
using (true);

drop policy if exists "events_read_public_scheduled" on public.events;
create policy "events_read_public_scheduled"
on public.events for select
to anon
using (status = 'scheduled');

drop policy if exists "events_read_authenticated" on public.events;
create policy "events_read_authenticated"
on public.events for select
to authenticated
using (true);

drop policy if exists "events_insert_own" on public.events;
create policy "events_insert_own"
on public.events for insert
to authenticated
with check ((select auth.uid()) = creator_id);

drop policy if exists "events_update_own" on public.events;
create policy "events_update_own"
on public.events for update
to authenticated
using ((select auth.uid()) = creator_id)
with check ((select auth.uid()) = creator_id);

drop policy if exists "events_delete_own" on public.events;
create policy "events_delete_own"
on public.events for delete
to authenticated
using ((select auth.uid()) = creator_id);

drop policy if exists "participants_read_authenticated" on public.event_participants;
create policy "participants_read_authenticated"
on public.event_participants for select
to authenticated
using (true);

drop policy if exists "saved_events_read_own" on public.saved_events;
create policy "saved_events_read_own"
on public.saved_events for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "saved_events_insert_own" on public.saved_events;
create policy "saved_events_insert_own"
on public.saved_events for insert
to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "saved_events_delete_own" on public.saved_events;
create policy "saved_events_delete_own"
on public.saved_events for delete
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "event_messages_read_members" on public.event_messages;
create policy "event_messages_read_members"
on public.event_messages for select
to authenticated
using (public.is_event_participant(event_id));

drop policy if exists "event_messages_insert_members" on public.event_messages;
create policy "event_messages_insert_members"
on public.event_messages for insert
to authenticated
with check (
  (select auth.uid()) = sender_id
  and public.is_event_participant(event_id)
);

drop policy if exists "notifications_read_own" on public.notifications;
create policy "notifications_read_own"
on public.notifications for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "notifications_update_own" on public.notifications;
create policy "notifications_update_own"
on public.notifications for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "notifications_delete_own" on public.notifications;
create policy "notifications_delete_own"
on public.notifications for delete
to authenticated
using ((select auth.uid()) = user_id);

grant usage on schema public to anon, authenticated;
grant select on public.sports to anon, authenticated;
grant select, insert, update on public.profiles to authenticated;
grant select on public.events to anon, authenticated;
grant insert, update, delete on public.events to authenticated;
grant select on public.event_participants to authenticated;
revoke insert, update, delete on public.event_participants from anon, authenticated;
grant select, insert, delete on public.saved_events to authenticated;
grant select, insert on public.event_messages to authenticated;
grant select, update, delete on public.notifications to authenticated;
grant usage, select on sequence public.event_messages_id_seq to authenticated;
grant usage, select on sequence public.notifications_id_seq to authenticated;

revoke all on function public.join_event(uuid, text, text) from public, anon;
grant execute on function public.join_event(uuid, text, text) to authenticated;
revoke all on function public.leave_event(uuid) from public, anon;
grant execute on function public.leave_event(uuid) to authenticated;
revoke all on function public.is_event_participant(uuid) from public, anon;
grant execute on function public.is_event_participant(uuid) to authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'avatars',
  'avatars',
  true,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "avatars_public_read" on storage.objects;
create policy "avatars_public_read"
on storage.objects for select
to anon, authenticated
using (bucket_id = 'avatars');

drop policy if exists "avatars_insert_own_folder" on storage.objects;
create policy "avatars_insert_own_folder"
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = (select auth.uid())::text
);

drop policy if exists "avatars_update_own_folder" on storage.objects;
create policy "avatars_update_own_folder"
on storage.objects for update
to authenticated
using (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = (select auth.uid())::text
)
with check (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = (select auth.uid())::text
);

drop policy if exists "avatars_delete_own_folder" on storage.objects;
create policy "avatars_delete_own_folder"
on storage.objects for delete
to authenticated
using (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = (select auth.uid())::text
);

alter table public.events replica identity full;
alter table public.event_participants replica identity full;
alter table public.event_messages replica identity full;
alter table public.notifications replica identity full;

do $$
begin
  alter publication supabase_realtime add table public.events;
exception when duplicate_object then null;
end;
$$;

do $$
begin
  alter publication supabase_realtime add table public.event_participants;
exception when duplicate_object then null;
end;
$$;

do $$
begin
  alter publication supabase_realtime add table public.event_messages;
exception when duplicate_object then null;
end;
$$;

do $$
begin
  alter publication supabase_realtime add table public.notifications;
exception when duplicate_object then null;
end;
$$;

commit;
